config/routes.rb
Rails.application.routes.draw do

  root to: 'lessons#index', as: 'root'

  get '/lesson', to: 'lessons#show'
  get '/win', to: 'lessons#win'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'

  resources :learners do
    resources :logs
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/learner.rb
class Learner < ApplicationRecord

  belongs_to :user
  
  has_many :logs

end

app/models/log.rb
class Log < ApplicationRecord

  belongs_to :learner

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :learners

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/learners_controller.rb
class LearnersController < ApplicationController

  def index
    @user = current_user
    @learners = @user.learners
  end

  def new
    @user = User.find_by_id(params[:id])
    @learner = Learner.new
  end

  def create
    @user = User.find_by_id(params[:id])
    @learner = Learner.new(learner_params)

    @learner.save
      redirect_to @learner
  end

  def show
    @user = current_user
    @learner = @user.learners.find_by_id(params[:id])
  end

  def edit
    @user = User.find_by_id(params[:id])
    @learner = Learner.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    @learner = Learner.find_by_id(params[:id])
    if @learner.update(learner_params)
      redirect_to learner_path(@learner)
    else
      redirect_to :back
    end
  end

  def destroy
    @learner = Learner.find_by_id(params[:id])
    @learner.delete
    redirect_to learners_path
  end

  private

  def learner_params
    params.require(:learner).permit(:name, :age, :image, :parent_guardian, :contact_info, :user_id, :inventory_of_favorites)
  end



end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    render :index
  end

  def show
    render :show
  end

  def win
    render :win
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController

  def index
    @learner = Learner.find(params[:learner_id])
    @logs = @learner.logs
  end

  def show
    @learner = Learner.find_by_id(params[:learner_id])
    @log = @learner.logs.find(params[:id])
  end

  def new
    @learner = Learner.find_by_id(params[:learner_id])
    @log = Log.new
  end

  def create
    @learner = Learner.find_by_id(params[:learner_id])
    @log = @learner.logs.create(log_params)
    if @learner.logs.push(@log)
      redirect_to learner_log_path(@learner, @log)
    else
      redirect_to :back
    end
  end

  def edit
    @learner = Learner.find_by_id(params[:learner_id])
    @log = @learner.logs.find(params[:id])
  end

  def update
    @learner = Learner.find_by_id(params[:learner_id])
    @log = @learner.logs.find(params[:id])
    if @log.update(log_params)
      redirect_to learner_log_path(@learner, @log)
    else
      redirect_to :back
    end
  end

  def destroy
    @learner = Learner.find_by_id(params[:learner_id])
    @log = @learner.logs.find(params[:id])
    @log.delete
    redirect_to learner_logs_path
  end

  private

  def log_params
    params.require(:log).permit(:title, :starting_mood, :level, :verbal_word_approximation, :physically_identify, :good_choices, :action, :observations, :comments, :date, :learner_id)
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    render :show
  end

  def index
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def image_tag(img , options={})
    path = "#{Rails.root}/app/assets/images/#{img}"
    img = "egg_default.png"  unless img.present?
    p super(img, options)
  end

end

app/helpers/learners_helper.rb
module LearnersHelper
  def learners_by_age
  bar_chart @learners.group(:age).count, height: '500px', library: {
    title: {text: 'Learners by age', x: -20},
    yAxis: {
       allowDecimals: false,
       title: {
           text: 'Ages count'
       }
    },
    xAxis: {
       title: {
           text: 'Age'
       }
    }
  }
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/logs_helper.rb
module LogsHelper
  def learners_by_starting_mood
  line_chart @learners.group(:starting_mood).count, height: '500px', library: {
    title: {text: 'Logs by Mood', x: -20},
    yAxis: {
       allowDecimals: false,
       title: {
           text: 'Mood count'
       }
    },
    xAxis: {
       title: {
           text: 'Date'
       }
    }
  }
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    if current_user == nil
      redirect_to login_path
    end
  end

  def logout
    @current_user = session[:user_id] = nil
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Egg</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'highcharts.js', 'chartkick' %>
    <meta name="viewport" content="width=device-width,
        user-scalable=no, initial-scale=1, maximum-scale=1, user-scalable=0" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="translucent" />



    <div class="ui stackable menu">
      <div>
        <%= link_to '/', :class => 'item' do %>
        <%= image_tag 'egg_drive.png' %>
        <% end %>
      </div>
      <a>
        <% if !current_user %>
        <%= link_to 'Login', '/login', :class => 'item' %>
      </a>
      <a>
        <%= link_to 'Signup', '/signup', :class => 'item' %>
        <% else %>
        <div class="right menu">
          <a>
            <%= link_to "Welcome, #{current_user.name} !", root_path, :class => 'item' %>
          </a>
          <a>
            <%= link_to 'Logout', '/logout', :class => 'item' %>
          </a>
          <a>
            <%= link_to 'Learners', learners_path, :class => 'item' %>
          </a>
          <% end %>
        </div>
      </div>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/learners/edit.html.erb
<div class="ui raised very padded text container segment centered">
  <%= form_for @learner do |f| %>
  <div class="ui form">
    <div class="equal width fields">
        <div class="field">
        <label>Learner Name:</label>
        <%= f.text_field :name, :placeholder => 'Learner First & Last Name' %>
      </div>
      <div class="field">
        <label>Learner Age:</label>
        <%= f.text_field :age, :placeholder => '6' %>
      </div>
      <div class="field">
        <label>Learner Image:</label>
        <%= f.text_field :image, :placeholder => 'Image URL' %>
      </div>
    </div>
    <div class="equal width fields">
      <div class="field">
        <label>Learner Parent/Guardian:</label>
        <%= f.text_field :parent_guardian, :placeholder => 'Parent / Guardian Name' %>
      </div>
      <div class="field">
        <label>Parent/Guardian Contact Information:</label>
        <%= f.text_field :contact_info, :placeholder => '(415) 707-77-77' %>
      </div>
      <div class="field">
        <label>Learner Moderator ID:</label>
        <%= f.text_field :user_id, :placeholder => '1' %>
      </div>
    </div>
    <div class="ui fluid field">
      <label>Inventory Of Favorite Things</label>
      <%= f.text_field :inventory_of_favorites, :placeholder => 'Blankie, Sherwin my Doll, My Dog Sparky' %>
    </div>
    <div class="ui fluid labeled buttons">
      <button class="ui left labeled icon postive button">
        <i class="pointing left icon"></i>
        <%= link_to :back, 'Cancel' %>
      </button>
      <div class="or"></div>
      <button class="ui right labeled icon button">
          <%= f.submit 'Update Learner', :class => 'ui right labeled button' %>
        <i class="hand peace icon"></i>
      </button>
    </div>
  </div>
  <% end %>
</div>

app/views/learners/index.html.erb
  <%= bar_chart @learners.group(:age).count %>

<div class="ui grid container">
<div class="row">
  <div class="four wide column">
    <div class="ui small vertical menu">
      <div class="item">
        <%= image_tag 'egg_logo.png'%>
      </div>
        <a class="item">Learners</a>
        <a class="item">Logs</a>
        <a class="item">Case Manager Page</a>
        <a class="item">
          <i class="grid layout icon"></i> Resources
        </a>
        <div class="ui link card">
          <div class="fluid ui content">
            <h2 class="ui centered header">
              <i class="hand peace icon"></i>
            </h2>
            <div class="fluid ui bottom attached button">
              <i class="add icon"></i>
              <a href="<%= new_learner_path %>">Add A Learner</a>
            </div>
          </div>
        </div>
      </div>
  </div>

  <div class="twelve wide column">
    <% @learners.each do |learner| %>
    <div class="fluid ui large card">
      <div class="ui items">
        <div class="fluid ui item">
          <div class="ui large image">
            <%= image_tag "#{learner.image}" %>
          </div>
        </div>
      <div class="ui fluid middle aligned content">
        <div class="header">
          <%= link_to "#{learner.name}", learner_path(learner)%>
        </div>
        <div class="description">
          <div class="meta">
            <span class="category">Age: 4</span>
            <span class="right floated time"><%= learner.user_id %></span>
          </div>
        </div>
      </div>
      </div>
      Emergency Contact:
      <strong><%= learner.parent_guardian %>: </strong> <%= learner.contact_info %>
        <br>
        Inventory of Favorite Things: <%= learner.inventory_of_favorites %>
      <a href="<%= edit_learner_path(learner) %>" class="fluid ui button">Edit Learner Information</a>
    </div>

    <% end %>
  </div>
</div>
</div>

app/views/learners/new.html.erb
<div class="ui raised very padded text container segment centered">
  <%= form_for @learner do |f| %>
  <div class="ui form">
    <div class="equal width fields">
        <div class="field">
        <label>Learner Name:</label>
        <%= f.text_field :name, :placeholder => 'Learner First & Last Name' %>
      </div>
      <div class="field">
        <label>Learner Age:</label>
        <%= f.text_field :age, :placeholder => '6' %>
      </div>
      <div class="field">
        <label>Learner Image:</label>
        <%= f.text_field :image, :placeholder => 'Image URL' %>
      </div>
    </div>
    <div class="equal width fields">
      <div class="field">
        <label>Learner Parent/Guardian:</label>
        <%= f.text_field :parent_guardian, :placeholder => 'Parent / Guardian Name' %>
      </div>
      <div class="field">
        <label>Parent/Guardian Contact Information:</label>
        <%= f.text_field :contact_info, :placeholder => '(415) 707-77-77' %>
      </div>
      <div class="field">
        <label>Learner Moderator ID:</label>
        <%= f.text_field :user_id, :placeholder => '1' %>
      </div>
    </div>
    <button class="fluid ui button">
      <i class="hand peace icon"></i>
        <%= f.submit "Save Learner", :class => 'ui button' %>
    </button>
  </div>
  <% end %>

</div>

app/views/learners/show.html.erb
<div class="ui raised padded text container segment">
  <div class="ui fluid grid">

    <div class="ui six wide column">
      <div class="ui fluid card">
        <h1> <%= @learner.name %> </h1>
        <div class="content">
          <div class="header"><%= @learner.contact_info %></div>
          <div class="meta"><%= @learner.parent_guardian %></div>
          <div class="description">
            <%= @learner.name %>'s Age is '<%= @learner.age %>
          </div>
        </div>
        <%= link_to "Show #{@learner.name}'s Logs", learner_logs_path(@learner), :class => 'fluid ui button' %>
      </div>
      <div class="ui segment">
        Inventory of Favorite Things:
        <p><%= @learner.inventory_of_favorites %></p>
      </div>
    </div>
    <div class="ui ten wide column">
      <%= image_tag(@learner.image)%>
    </div>

    <a href="<%= edit_learner_path(@learner) %>" class="fluid ui button">Edit Learner Information</a>

  </div>

</div>

app/views/lessons/index.html.erb
<style type="text/css">
body { display: block;
         background-color: #007ced;
         background: linear-gradient(to bottom, #007ced 1%,#cce7ff 100%);
       }
#cloud-intro {
  margin: 0 auto;
  background: url(http://static.radulescu.me/examples/clouds/clouds1000.png);
  background: url(http://static.radulescu.me/examples/clouds/clouds1000.png) 0 200px,
  url(http://static.radulescu.me/examples/clouds/clouds1200_1.png) 0 300px,
  url(http://static.radulescu.me/examples/clouds/clouds1000_blur3.png) 100px 250px;
  animation: wind 20s linear infinite;
  position: relative;
  height: 100%;
  width: 100%;
  height: 100%;
  min-width: 500px;
  min-height: 500px;
  margin: 0;
  padding: 0;
  overflow: hidden;
}

@keyframes wind{
  0% {
    background-position: 0 200px, 0 300px, 100px 250px;
    }
  100% {
    background-position: 1000px 200px, 1200px 300px, 1100px 250px;
    }
}
</style>




<div class="container">
<div id="cloud-intro">
  <h2 class="ui center aligned icon header">
  <i class="gamepad users icon"></i>
  <%= image_tag 'egg_logo.png', :class => 'ui large image' %>
  <br>
  Emotional Gauge Game!
  </h2>
<div class="ui left floated vertical labeled icon menu">
    <a>
      <%= link_to '/', :class => 'item' do %>
      <i class="heart icon"></i>
      <% end %>
      Emotional
    </a>
    <a>
      <%= link_to '/login', :class => 'item' do %>
      <i class="history icon"></i>
      <% end %>
      Gauge
    </a>
    <a>
      <%= link_to '/lesson', :class => 'item' do %>
      <i class="gamepad icon"></i>
      <% end %>
      Game
    </a>
</div>



</div>
</div>

app/views/lessons/win.html.erb
<h1>win</h1>

app/views/logs/edit.html.erb
<div class="ui raised very padded text container segment centered">
  <%= form_for([@learner, @log]) do |f| %>
  <div class="ui form">
    <div class="equal width fields">
        <div class="field">
        <label>  Title :</label>
        <%= f.text_field :title, :placeholder => 'Lesson: Set' %>
      </div>
      <div class="field">
        <label>  Learner Starting mood: </label>
        <%= f.text_field :starting_mood, :placeholder => 'Happy'  %>
      </div>
      <div class="field">
        <label>Level: </label>
        <%= f.text_field :level, :placeholder => '1' %>
      </div>
    </div>
    <div class="equal width fields">
      <div class="field">
        <label>Can Verbally make word approximation: </label>
        <%= f.text_field :verbal_word_approximation, :placeholder => 'true' %>
      </div>
      <div class="field">
        <label> Can Physically Identify or Point to:  </label>
        <%= f.text_field :physically_identify, :placeholder => 'true'  %>
      </div>
      <div class="field">
        <label>Good Choices Used :</label>
        <%= f.text_field :good_choices, :placeholder => 'I need Blankie, I need Hug, Outside Play' %>
      </div>
    </div>
    <div class="equal width fields">
      <div class="field">
        <label>Action : </label>
        <%= f.text_field :action, :placeholder => 'Go get Blankie, Give someone a hug'  %>
      </div>
      <div class="field">
        <label>Observations :</label>
        <%= f.text_field :observations, :placeholder => 'Learner was...' %>
      </div>
      <div class="field">
        <label>Comments :</label>
        <%= f.text_field :comments, :placeholder => 'The Lesson took...' %>
      </div>
    </div>
    <div class="equal width fields">
      <div class="field">
        <label>Date of Log :</label>
        <%= f.text_field :date, :placeholder => '2016/11/11' %>
      </div>
      <div class="field">
        <label>Learner ID:</label>
        <%= f.text_field :learner_id, :placeholder => '1' %>
      </div>
    </div>
    <button class="fluid ui button">
      <i class="hand peace icon"></i>
        <%= f.submit "Edit Log", :class => 'ui button' %>
    </button>
  </div>
  <% end %>

</div>

app/views/logs/index.html.erb
<div class="segment">
  <%= line_chart Log.group(:starting_mood).group_by_day(:created_at).count %>
</div>
<div class="ui grid container">
  <div class="four wide column">
    <div class="ui small vertical menu">
      <div class="item">
        <%= image_tag 'egg_logo.png'%>
      </div>
      <a class="item">Learners</a>
      <a class="item">Logs</a>
      <a class="item">Case Manager Page</a>
      <a class="item">
        <i class="grid layout icon"></i> Resources
      </a>
      <div class="ui link card">
        <div class="fluid ui content">
          <h2 class="ui centered header">
            <i class="hand peace icon"></i>
          </h2>
          <div class="fluid ui bottom attached button">
            <i class="add icon"></i>
            <a href="<%= new_learner_log_path %>">Add A Log</a>
          </div>
        </div>
      </div>
    </div>

  </div>

<div class="sixteen wide column">
  <% @logs.each do |log| %>
  <div class=" ui fluid  segment">
    <div class="ui top attached button" tabindex="0">
      <%= link_to " #{log.title}", learner_log_path(@learner, log)%>
    </div>
    <div class="ui attached segment">
      <a class="ui ribbon label">
        <i class="gamepad icon"></i>
        Level: <%= log.level %>
      </a>
      <div class="ui icon center aligned dividing header">
        <i class="settings icon"></i>
        <div class="content">
          <div class="sub header">Date of Log : <%= log.date %> </div>
        </div>
      </div>
      <div class="ui block header">
        <i class="settings icon"></i>
        <div class="content">
          <%= log.starting_mood %>
          <div class="sub header">Learners Starting Mood</div>
        </div>
      </div>
      <div class="ui segment">
        <div class="ui top attached label">Comments</div>
        <p>
          <%= log.comments %>
        </p>
      </div>
      <button class="ui right button">
        <i class="pause icon"></i>
        <%= link_to "Delete", learner_log_path(@learner, log), method: :delete %>
      </button>
    </div>
  </div>
  <% end %>

</div>

</div>

app/views/logs/new.html.erb
<div class="ui raised very padded text container segment centered">
  <%= form_for([@learner, @log]) do |f| %>
  <div class="ui form">
    <div class="equal width fields">
        <div class="field">
        <label>  Title :</label>
        <%= f.text_field :title, :placeholder => 'Lesson: Set' %>
      </div>
      <div class="field">
        <label>  Learner Starting mood: </label>
        <%= f.text_field :starting_mood, :placeholder => 'Happy'  %>
      </div>
      <div class="field">
        <label>Level: </label>
        <%= f.text_field :level, :placeholder => '1' %>
      </div>
    </div>
    <div class="equal width fields">
      <div class="field">
        <label>Can Verbally make word approximation: </label>
        <%= f.text_field :verbal_word_approximation, :placeholder => 'true' %>
      </div>
      <div class="field">
        <label> Can Physically Identify or Point to:  </label>
        <%= f.text_field :physically_identify, :placeholder => 'true'  %>
      </div>
      <div class="field">
        <label>Good Choices Used :</label>
        <%= f.text_field :good_choices, :placeholder => 'I need Blankie, I need Hug, Outside Play' %>
      </div>
    </div>
    <div class="equal width fields">
      <div class="field">
        <label>Action : </label>
        <%= f.text_field :action, :placeholder => 'Go get Blankie, Give someone a hug'  %>
      </div>
      <div class="field">
        <label>Observations :</label>
        <%= f.text_field :observations, :placeholder => 'Learner was...' %>
      </div>
      <div class="field">
        <label>Comments :</label>
        <%= f.text_field :comments, :placeholder => 'The Lesson took...' %>
      </div>
    </div>
    <div class="equal width fields">
      <div class="field">
        <label>Date of Log :</label>
        <%= f.text_field :date, :placeholder => '2016/11/11' %>
      </div>
      <div class="field">
        <label>Learner ID:</label>
        <%= f.text_field :learner_id, :placeholder => '1' %>
      </div>
    </div>
    <button class="fluid ui button">
      <i class="hand peace icon"></i>
        <%= f.submit "Save Log", :class => 'ui button' %>
    </button>
  </div>
  <% end %>

</div>

app/views/logs/show.html.erb
<div class="segment">
  <%= line_chart Log.group(:starting_mood).group_by_day(:created_at).count %>

</div>
<div class="ui container">
  <div class="ui segment">
    <a class="ui ribbon label">
      <i class="gamepad icon"></i>
      Level: <%= @log.level %>
    </a>

    Title: <%= @log.title %>
    Date of Log: <%= @log.date %>


    <div class="ui segment">
      <div class="ui dividing header">
        <i class="settings icon"></i>
        <div class="content">
          <%= @log.starting_mood %>
          <div class="sub header">Learner Starting mood </div>
        </div>
      </div>
    </div>

    <div class="ui segment">
      <div class="ui top attached label">1. Can Identify Emotion</div>
      <p>
        <i class="assistive listening systems icon"></i>
        Can Verbally Express:
        <%= @log.verbal_word_approximation %>
          |
          <i class="sign language icon"></i>
          Can Physically Identify:
          <%= @log.physically_identify %>

      </p>
    </div>


    <div class="ui segment">
      <div class="ui top attached label">2. Can Make Good Choices</div>
      <p> Good Choices Used: <%= @log.good_choices %></p>
    </div>

    <div class="ui segment">
      <div class="ui top attached label">3. Can Act Out Good Choices</div>
      <p> Assistive Instructions Given: <%= @log.good_choices %></p>
    </div>

    <div class="ui segment">
      <a class="ui ribbon label">Observations:</a>
      <p>
        <%= @log.observations %>
      </p>
    </div>
    <div class="ui segment">
      <a class="ui ribbon label">Comments: </a>
      <p>
        <%= @log.comments %>
      </p>
    </div>

  </div>
  <%= link_to "Delete", learner_log_path, method: :delete %>
  |
  <a href="<%= edit_learner_log_path(@learner, @log) %>" class="button expanded">Edit Log</a> |

</div>

app/views/users/new.html.erb
<div class="ui raised very padded text container segment centered">
  <h2 class="ui header centered">

    <%= image_tag 'egg_drive.png', class: "ui tiny image" %>
  </h2>
  <h2 class="ui header centered">
    <%= image_tag 'egg_logo.png', class: "ui tiny image" %>
  </h2>
  <h3 class="ui header centered">
    Sign Up!
  </h3>
  <div class="ui large form">
    <%= form_for :user, url: '/users' do |f| %>
    <div class="two fields">
      <div class="field">
        <label>First & Last Name</label>
        <%= f.text_field :name, :placeholder => 'First & Last Name' %>
      </div>
      <div class="ui right icon input">
        <i class="user icon"></i>
      </div>
      <div class="field">
        <label>E-mail</label>
        <%= f.text_field :email, :placeholder => 'email@address.com' %>
      </div>
      <div class="ui right icon input">
        <i class="mail icon"></i>
      </div>
    </div>
    <div class="two fields">
      <div class="field">
        <label>Password</label>
        <%= f.password_field :password, :placeholder => 'Password' %>
      </div>
      <div class="ui right icon input">
        <i class="privacy icon"></i>
      </div>
      <div class="field">
        <label>Password Confirmation</label>
        <%= f.password_field :password_confirmation, :placeholder => 'Password Confirmation' %>
      </div>
      <div class="ui right icon input">
        <i class="lock icon"></i>
      </div>
    </div>
  <div class="inline fields">
    <label for="fruit">Learner Relation:</label>
    <div class="field">
      <div class="ui radio checkbox">
        <input type="radio" name="case_manager" checked="" tabindex="0" class="hidden">
        <label>Case Manager</label>
      </div>
    </div>
    <div class="field">
      <div class="ui radio checkbox">
        <input type="radio" name="speech_therapist" tabindex="0" class="hidden">
        <label>Speech Therapist</label>
      </div>
    </div>
    <div class="field">
      <div class="ui radio checkbox">
        <input type="radio" name="occupational_therapist" tabindex="0" class="hidden">
        <label>Occupational Therapist</label>
      </div>
    </div>
    <div class="field">
      <div class="ui radio checkbox">
        <input type="radio" name="parent_guardian" tabindex="0" class="hidden">
        <label>Parent or Guardian</label>
      </div>
      </div>
  </div>
    <%= f.submit "Submit", :class => 'ui fluid medium submit button' %>
    <% end %>


  </div>
</div>